name: 'Inc Semver'
description: 'Determine the next semver based on commits to a given path and the last tag. Tags are prefixed with the package name. Useful for monorepos.'
inputs:
  token:
    description: 'Github Token'
    required: true
  directory:
    description: 'Directory where package.json is located'
    required: true
outputs:
  latest-version:
    description: 'Latest version'
  latest-tag:
    description: 'Latest tag'
  next-version:
    description: 'Next version'
  next-tag:
    description: 'Next tag'
runs:
  using: 'node12'
  main: 'src/action.js'
