name: 'Increment SemVer Action'
description: 'Determine the next semver based on commits to a given path and the last tag.'
inputs:
  token:
    description: 'Github Token'
    required: true
  directory:
    description: 'Directory where package.json is located'
    default: '.'
    required: false
  prefix:
    description: 'Prefix for next tag'
    default: '<package name>@v'
outputs:
  latestVersion:
    description: 'Latest version'
  latestTag:
    description: 'Latest tag'
  nextVersion:
    description: 'Next version'
  nextTag:
    description: 'Next tag'
  changeLog:
    description: 'List of commits'
runs:
  using: 'node12'
  main: 'src/action.js'
branding:
  icon: 'box'
  color: 'gray-dark'
