name: Release

on:
  push:
    branches:
      - master

jobs:
  get:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: trs/inc-semver-action@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          directory: .
