name: Release

on:
  push:
    branches:
      - master

jobs:
  get:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Determine Version
        uses: trs/inc-semver-action@6c26fd32a5dd93d2481b91bd1b14a7ff584e98de
        id: semver
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: .
          prefix: "v"
      - run: |
          echo latestVersion: ${{ steps.semver.outputs.latestVersion }}
          echo latestTag: ${{ steps.semver.outputs.latestTag }}
          echo nextVersion: ${{ steps.semver.outputs.nextVersion }}
          echo nextTag: ${{ steps.semver.outputs.nextTag }}
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.nextTag }}
          release_name: Release v${{ steps.semver.outputs.nextVersion }}
          body: ${{ steps.semver.outputs.latestVersion }} -> ${{ steps.semver.outputs.nextVersion }}
