name: Release

on:
  push:
    branches:
      - master

jobs:
  get:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Determine Version
        uses: trs/inc-semver-action@master
        id: version
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          directory: .
      - run: |
          echo latestVersion: ${{ steps.semver.outputs.latestVersion }}
          echo latestTag: ${{ steps.semver.outputs.latestTag }}
          echo nextVersion: ${{ steps.semver.outputs.nextVersion }}
          echo nextTag: ${{ steps.semver.outputs.nextTag }}
